# Set your personal kitty configuration here

confirm_os_window_close 0
allow_remote_control yes
map ctrl+shift+h clear
map ctrl+shift+j clear
map ctrl+shift+k none
map ctrl+shift+l none

map alt+h clear
map alt+j clear
map alt+k none
map alt+l none
